import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import ChatScreen from "../components/ChatScreen"
import styled from "styled-components"

export default function Home() {
  
  return (
    <Container>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <ChatContainer>
            <Image src="/whatsapp-home.jpg" height={250} width={250} objectFit="cover" alt="Whatsapp intro"/>
            <h2>Keep your phone connected</h2>
            <p>WhatsApp connects to your phone to sync messages. To reduce data usage, connect your phone to Wi-Fi.</p>
      </ChatContainer>
    </Container>
  )
}
const Container = styled.div`
    display: flex;
`
const ChatContainer = styled.div`
    display: flex;
    flex: 1;
    overflow: scroll;
    height: 100vh;

    ::-webkit-scrollbar{
        display: none;
    }
    -ms-overflow-style: none;
    scrollbar-width: none;
    background-color: #F8F8F8;
    flex-direction: column;
    justify-content: center;
    align-items: center;  

    h2{
      color: #727372;
      font-weight: normal
    }

    p{
      color: #b7b9bb;
      text-align: center;
    }

`
